<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EnergySource;
use App\Models\User;
use Carbon\Carbon;

class EnergySourceSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::take(3)->get();
        if ($users->isEmpty()) {
            $this->command->warn('⚠️ No hay usuarios disponibles. Saltando EnergySourceSeeder.');
            return;
        }

        $sources = [
            [
                'name' => 'Parque Solar Fotovoltaico "Sol de Andalucía"',
                'description' => 'Granja solar fotovoltaica de gran escala ubicada en Andalucía con tecnología de última generación.',
                'source_type' => EnergySource::SOURCE_TYPE_SOLAR,
                'status' => EnergySource::STATUS_ACTIVE,
                'energy_category' => EnergySource::ENERGY_CATEGORY_RENEWABLE,
                'installed_capacity_mw' => 100.00,
                'operational_capacity_mw' => 95.50,
                'efficiency_rating' => 22.5,
                'availability_factor' => 98.2,
                'capacity_factor' => 25.8,
                'annual_production_mwh' => 220000.00,
                'monthly_production_mwh' => 18333.33,
                'daily_production_mwh' => 602.74,
                'hourly_production_mwh' => 25.11,
                'location_address' => 'Finca Solar Andalucía, Sevilla',
                'latitude' => 37.3891,
                'longitude' => -5.9845,
                'region' => 'Andalucía',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(3),
                'expected_lifespan_years' => 25,
                'construction_cost' => 80000000.00,
                'operational_cost_per_mwh' => 15.50,
                'maintenance_cost_per_mwh' => 8.25,
                'technical_specifications' => 'Paneles monocristalinos de 550W, inversores string de 1MW',
                'environmental_impact' => 'Reducción de 110,000 toneladas de CO2 anuales',
                'regulatory_compliance' => 'Cumple normativa RD 244/2019 y directivas europeas',
                'safety_features' => 'Sistema de desconexión automática, vallado perimetral',
                'equipment_details' => '15,000 paneles solares, 100 inversores, sistema de seguimiento',
                'maintenance_schedule' => 'Inspección mensual, limpieza trimestral, revisión anual',
                'performance_metrics' => ['Factor de capacidad', 'Disponibilidad', 'Eficiencia energética'],
                'environmental_data' => ['Emisiones evitadas', 'Huella de carbono', 'Impacto ambiental'],
                'regulatory_documents' => ['Permisos ambientales', 'Licencias de explotación', 'Certificados de origen'],
                'tags' => ['solar', 'fotovoltaica', 'andalucía', 'renovable'],
                'managed_by' => $users->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subYears(2),
                'notes' => 'Fuente de energía solar de referencia en Andalucía',
            ],
            [
                'name' => 'Parque Eólico "Vientos del Norte"',
                'description' => 'Parque eólico terrestre con turbinas de última generación en la costa norte.',
                'source_type' => EnergySource::SOURCE_TYPE_WIND,
                'status' => EnergySource::STATUS_ACTIVE,
                'energy_category' => EnergySource::ENERGY_CATEGORY_RENEWABLE,
                'installed_capacity_mw' => 80.00,
                'operational_capacity_mw' => 78.50,
                'efficiency_rating' => 45.2,
                'availability_factor' => 95.8,
                'capacity_factor' => 42.5,
                'annual_production_mwh' => 298000.00,
                'monthly_production_mwh' => 24833.33,
                'daily_production_mwh' => 816.44,
                'hourly_production_mwh' => 34.02,
                'location_address' => 'Costa del Norte, Cantabria',
                'latitude' => 43.4623,
                'longitude' => -3.8099,
                'region' => 'Cantabria',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(2),
                'expected_lifespan_years' => 20,
                'construction_cost' => 120000000.00,
                'operational_cost_per_mwh' => 18.75,
                'maintenance_cost_per_mwh' => 12.50,
                'technical_specifications' => 'Turbinas de 4MW, altura de buje 120m, diámetro de rotor 150m',
                'environmental_impact' => 'Reducción de 149,000 toneladas de CO2 anuales',
                'regulatory_compliance' => 'Cumple normativa eólica nacional y europea',
                'safety_features' => 'Sistema de parada automática, señalización aeronáutica',
                'equipment_details' => '20 turbinas eólicas, subestación eléctrica, sistema SCADA',
                'maintenance_schedule' => 'Inspección trimestral, mantenimiento anual, revisión de 5 años',
                'performance_metrics' => ['Factor de capacidad', 'Disponibilidad técnica', 'Producción anual'],
                'environmental_data' => ['Emisiones evitadas', 'Impacto en avifauna', 'Ruido ambiental'],
                'regulatory_documents' => ['Permisos ambientales', 'Licencias de explotación', 'Estudios de impacto'],
                'tags' => ['eolica', 'cantabria', 'renovable', 'costa'],
                'managed_by' => $users->skip(1)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subMonths(18),
                'notes' => 'Parque eólico de alta eficiencia en zona de vientos constantes',
            ],
            [
                'name' => 'Central Hidroeléctrica "Río Verde"',
                'description' => 'Central hidroeléctrica de embalse con turbinas Francis de alta eficiencia.',
                'source_type' => EnergySource::SOURCE_TYPE_HYDROELECTRIC,
                'status' => EnergySource::STATUS_ACTIVE,
                'energy_category' => EnergySource::ENERGY_CATEGORY_RENEWABLE,
                'installed_capacity_mw' => 50.00,
                'operational_capacity_mw' => 48.75,
                'efficiency_rating' => 92.8,
                'availability_factor' => 98.5,
                'capacity_factor' => 65.2,
                'annual_production_mwh' => 285000.00,
                'monthly_production_mwh' => 23750.00,
                'daily_production_mwh' => 780.82,
                'hourly_production_mwh' => 32.53,
                'location_address' => 'Embalse Río Verde, Sierra Nevada, Granada',
                'latitude' => 37.0000,
                'longitude' => -3.5000,
                'region' => 'Andalucía',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(8),
                'expected_lifespan_years' => 50,
                'construction_cost' => 150000000.00,
                'operational_cost_per_mwh' => 12.25,
                'maintenance_cost_per_mwh' => 6.75,
                'technical_specifications' => 'Turbinas Francis de 25MW, embalse de regulación',
                'environmental_impact' => 'Reducción de 142,500 toneladas de CO2 anuales',
                'regulatory_compliance' => 'Cumple normativa hidroeléctrica y ambiental',
                'safety_features' => 'Sistema de alivio de presión, monitoreo sísmico',
                'equipment_details' => '2 turbinas Francis, generadores síncronos, sistema de control',
                'maintenance_schedule' => 'Inspección mensual, mantenimiento semestral, revisión anual',
                'performance_metrics' => ['Factor de capacidad', 'Disponibilidad', 'Eficiencia hidráulica'],
                'environmental_data' => ['Impacto en ecosistemas acuáticos', 'Gestión de caudales'],
                'regulatory_documents' => ['Concesión hidroeléctrica', 'Permisos ambientales', 'Plan de gestión'],
                'tags' => ['hidroelectrica', 'granada', 'renovable', 'embalse'],
                'managed_by' => $users->skip(2)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subYears(7),
                'notes' => 'Central hidroeléctrica de referencia con alta disponibilidad',
            ],
            [
                'name' => 'Planta de Biomasa "Energía Verde"',
                'description' => 'Planta de generación eléctrica mediante combustión de biomasa forestal.',
                'source_type' => EnergySource::SOURCE_TYPE_BIOMASS,
                'status' => EnergySource::STATUS_ACTIVE,
                'energy_category' => EnergySource::ENERGY_CATEGORY_RENEWABLE,
                'installed_capacity_mw' => 25.00,
                'operational_capacity_mw' => 24.00,
                'efficiency_rating' => 35.5,
                'availability_factor' => 92.0,
                'capacity_factor' => 85.5,
                'annual_production_mwh' => 187000.00,
                'monthly_production_mwh' => 15583.33,
                'daily_production_mwh' => 512.33,
                'hourly_production_mwh' => 21.35,
                'location_address' => 'Polígono Industrial, León',
                'latitude' => 42.5987,
                'longitude' => -5.5673,
                'region' => 'Castilla y León',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(4),
                'expected_lifespan_years' => 25,
                'construction_cost' => 60000000.00,
                'operational_cost_per_mwh' => 45.50,
                'maintenance_cost_per_mwh' => 18.75,
                'technical_specifications' => 'Caldera de lecho fluidizado, turbina de vapor, sistema de tratamiento de gases',
                'environmental_impact' => 'Reducción de 93,500 toneladas de CO2 anuales',
                'regulatory_compliance' => 'Cumple normativa de emisiones y biomasa',
                'safety_features' => 'Sistema de extinción automática, monitoreo de emisiones',
                'equipment_details' => 'Caldera de biomasa, turbina de vapor, sistema de tratamiento',
                'maintenance_schedule' => 'Inspección semanal, mantenimiento mensual, parada anual',
                'performance_metrics' => ['Factor de capacidad', 'Eficiencia de combustión', 'Emisiones'],
                'environmental_data' => ['Emisiones de CO2', 'Gestión de cenizas', 'Consumo de biomasa'],
                'regulatory_documents' => ['Permisos ambientales', 'Licencias de explotación', 'Certificados de biomasa'],
                'tags' => ['biomasa', 'leon', 'renovable', 'forestal'],
                'managed_by' => $users->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subYears(3),
                'notes' => 'Planta de biomasa con gestión sostenible de recursos forestales',
            ],
            [
                'name' => 'Central de Ciclo Combinado "Gas Natural"',
                'description' => 'Central térmica de ciclo combinado con turbinas de gas y vapor.',
                'source_type' => EnergySource::SOURCE_TYPE_FOSSIL_FUEL,
                'status' => EnergySource::STATUS_ACTIVE,
                'energy_category' => EnergySource::ENERGY_CATEGORY_NON_RENEWABLE,
                'installed_capacity_mw' => 400.00,
                'operational_capacity_mw' => 380.00,
                'efficiency_rating' => 58.5,
                'availability_factor' => 88.5,
                'capacity_factor' => 45.2,
                'annual_production_mwh' => 1584000.00,
                'monthly_production_mwh' => 132000.00,
                'daily_production_mwh' => 4339.73,
                'hourly_production_mwh' => 180.82,
                'location_address' => 'Polígono Industrial, Tarragona',
                'latitude' => 41.1189,
                'longitude' => 1.2445,
                'region' => 'Cataluña',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(6),
                'expected_lifespan_years' => 30,
                'construction_cost' => 400000000.00,
                'operational_cost_per_mwh' => 65.25,
                'maintenance_cost_per_mwh' => 25.50,
                'technical_specifications' => 'Turbinas de gas de 200MW, turbina de vapor de 200MW',
                'environmental_impact' => 'Emisiones controladas de CO2, NOx y SOx',
                'regulatory_compliance' => 'Cumple normativa de emisiones industriales',
                'safety_features' => 'Sistema de detección de fugas, extinción automática',
                'equipment_details' => '2 turbinas de gas, 1 turbina de vapor, generadores',
                'maintenance_schedule' => 'Inspección diaria, mantenimiento mensual, parada anual',
                'performance_metrics' => ['Factor de capacidad', 'Eficiencia térmica', 'Emisiones'],
                'environmental_data' => ['Emisiones de CO2', 'Consumo de gas natural', 'Eficiencia energética'],
                'regulatory_documents' => ['Permisos ambientales', 'Licencias de explotación', 'Certificados de emisiones'],
                'tags' => ['gas', 'tarragona', 'ciclo-combinado', 'termica'],
                'managed_by' => $users->skip(1)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subYears(5),
                'notes' => 'Central de ciclo combinado de alta eficiencia para respaldo del sistema',
            ],
        ];

        foreach ($sources as $source) {
            EnergySource::firstOrCreate(
                ['name' => $source['name']],
                $source
            );
        }

        $this->command->info('✅ EnergySourceSeeder ejecutado correctamente');
        $this->command->info('📊 Fuentes de energía creadas: ' . count($sources));
        $this->command->info('🎯 Tipos: Solar PV, Eólica Onshore, Hidroeléctrica, Biomasa, Gas Natural');
        $this->command->info('📈 Estados: Todas activas');
        $this->command->info('⚡ Capacidad total instalada: ' . number_format(collect($sources)->sum('installed_capacity_mw'), 2) . ' MW');
        $this->command->info('💰 Inversión total: €' . number_format(collect($sources)->sum('construction_cost'), 2));
        $this->command->info('📍 Regiones: Andalucía, Cantabria, Castilla y León, Cataluña');
        $this->command->info('🌱 Categorías: Renovables (4), No Renovables (1)');
        $this->command->info('📊 Datos realistas: Capacidades, eficiencias y métricas operativas');
    }
}
