<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EnergyPool;
use App\Models\User;
use Carbon\Carbon;

class EnergyPoolSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::take(3)->get();
        if ($users->isEmpty()) {
            $this->command->warn('⚠️ No hay usuarios disponibles. Saltando EnergyPoolSeeder.');
            return;
        }

        $pools = [
            [
                'pool_number' => 'POOL-TRADING-001',
                'name' => 'Pool de Trading Solar Madrid',
                'description' => 'Pool especializado en trading de energía solar fotovoltaica en la región de Madrid.',
                'pool_type' => EnergyPool::POOL_TYPE_TRADING,
                'status' => EnergyPool::STATUS_ACTIVE,
                'energy_category' => EnergyPool::ENERGY_CATEGORY_RENEWABLE,
                'total_capacity_mw' => 150.50,
                'available_capacity_mw' => 120.25,
                'reserved_capacity_mw' => 20.00,
                'utilized_capacity_mw' => 110.25,
                'efficiency_rating' => 92.5,
                'availability_factor' => 95.8,
                'capacity_factor' => 78.2,
                'annual_production_mwh' => 1200000.00,
                'monthly_production_mwh' => 100000.00,
                'daily_production_mwh' => 3287.67,
                'hourly_production_mwh' => 136.99,
                'location_address' => 'Parque Solar Madrid Norte, Carretera A-1, Km 15',
                'latitude' => 40.4168,
                'longitude' => -3.7038,
                'region' => 'Madrid',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(2),
                'expected_lifespan_years' => 25,
                'construction_cost' => 120000000.00,
                'operational_cost_per_mwh' => 25.50,
                'maintenance_cost_per_mwh' => 8.75,
                'technical_specifications' => 'Paneles monocristalinos de alta eficiencia, inversores centralizados',
                'environmental_impact' => 'Reducción de 600,000 kg CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa RD 244/2019',
                'safety_features' => 'Sistema de desconexión automática, vallado perimetral',
                'pool_members' => ['SolarTech Madrid', 'Energía Verde S.L.', 'Renovables del Norte'],
                'pool_operators' => ['Operador Principal', 'Operador de Respaldo'],
                'pool_governance' => ['Junta Directiva', 'Comité Técnico', 'Comité de Sostenibilidad'],
                'trading_rules' => ['Precio mínimo por MWh', 'Horarios de trading', 'Penalizaciones por incumplimiento'],
                'settlement_procedures' => ['Liquidación mensual', 'Garantías bancarias', 'Auditorías trimestrales'],
                'risk_management' => ['Seguros de responsabilidad', 'Cobertura de producción', 'Gestión de riesgos meteorológicos'],
                'performance_metrics' => ['Factor de capacidad', 'Disponibilidad', 'Eficiencia energética'],
                'environmental_data' => ['Emisiones evitadas', 'Huella de carbono', 'Impacto ambiental'],
                'regulatory_documents' => ['Permisos ambientales', 'Licencias de explotación', 'Certificados de origen'],
                'tags' => ['solar', 'trading', 'madrid', 'renovable'],
                'managed_by' => $users->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subMonths(6),
                'notes' => 'Pool de referencia para energía solar en Madrid',
            ],
            [
                'pool_number' => 'POOL-RESERVE-002',
                'name' => 'Pool de Reserva Eólica Galicia',
                'description' => 'Pool de reserva estratégica para energía eólica en Galicia.',
                'pool_type' => EnergyPool::POOL_TYPE_RESERVE,
                'status' => EnergyPool::STATUS_ACTIVE,
                'energy_category' => EnergyPool::ENERGY_CATEGORY_RENEWABLE,
                'total_capacity_mw' => 200.00,
                'available_capacity_mw' => 180.00,
                'reserved_capacity_mw' => 20.00,
                'utilized_capacity_mw' => 160.00,
                'efficiency_rating' => 88.2,
                'availability_factor' => 92.5,
                'capacity_factor' => 65.8,
                'annual_production_mwh' => 1500000.00,
                'monthly_production_mwh' => 125000.00,
                'daily_production_mwh' => 4109.59,
                'hourly_production_mwh' => 171.23,
                'location_address' => 'Parque Eólico Costa da Morte, A Coruña',
                'latitude' => 43.2627,
                'longitude' => -8.4115,
                'region' => 'Galicia',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(3),
                'expected_lifespan_years' => 20,
                'construction_cost' => 180000000.00,
                'operational_cost_per_mwh' => 22.75,
                'maintenance_cost_per_mwh' => 12.50,
                'technical_specifications' => 'Turbinas eólicas de 3.5 MW, altura de buje 120m',
                'environmental_impact' => 'Reducción de 750,000 kg CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa eólica nacional',
                'safety_features' => 'Sistema de parada automática, señalización aeronáutica',
                'pool_members' => ['Eólica Galicia', 'Vientos del Atlántico', 'Energía Marina S.L.'],
                'pool_operators' => ['Operador Eólico Principal'],
                'pool_governance' => ['Consejo de Administración', 'Comité Operativo'],
                'trading_rules' => ['Reserva mínima del 10%', 'Activación en 15 minutos'],
                'settlement_procedures' => ['Liquidación diaria', 'Garantías de reserva'],
                'risk_management' => ['Seguros de viento', 'Cobertura de producción'],
                'performance_metrics' => ['Factor de capacidad', 'Disponibilidad técnica'],
                'environmental_data' => ['Emisiones evitadas', 'Impacto en avifauna'],
                'regulatory_documents' => ['Permisos ambientales', 'Licencias de explotación'],
                'tags' => ['eolica', 'reserva', 'galicia', 'renovable'],
                'managed_by' => $users->skip(1)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subMonths(8),
                'notes' => 'Pool estratégico para estabilidad del sistema',
            ],
            [
                'pool_number' => 'POOL-BALANCING-003',
                'name' => 'Pool de Balanceo Hidroeléctrico',
                'description' => 'Pool especializado en servicios de balanceo del sistema eléctrico.',
                'pool_type' => EnergyPool::POOL_TYPE_BALANCING,
                'status' => EnergyPool::STATUS_ACTIVE,
                'energy_category' => EnergyPool::ENERGY_CATEGORY_HYBRID,
                'total_capacity_mw' => 75.25,
                'available_capacity_mw' => 70.00,
                'reserved_capacity_mw' => 5.25,
                'utilized_capacity_mw' => 65.00,
                'efficiency_rating' => 95.8,
                'availability_factor' => 98.2,
                'capacity_factor' => 85.5,
                'annual_production_mwh' => 600000.00,
                'monthly_production_mwh' => 50000.00,
                'daily_production_mwh' => 1643.84,
                'hourly_production_mwh' => 68.49,
                'location_address' => 'Central Hidroeléctrica del Duero, Zamora',
                'latitude' => 41.5035,
                'longitude' => -5.7448,
                'region' => 'Castilla y León',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subYears(5),
                'expected_lifespan_years' => 50,
                'construction_cost' => 95000000.00,
                'operational_cost_per_mwh' => 15.25,
                'maintenance_cost_per_mwh' => 5.75,
                'technical_specifications' => 'Turbinas Francis de 25 MW, embalse de regulación',
                'environmental_impact' => 'Reducción de 300,000 kg CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa hidroeléctrica',
                'safety_features' => 'Sistema de alivio de presión, monitoreo sísmico',
                'pool_members' => ['Hidroeléctrica del Duero', 'Energía Hidráulica S.L.'],
                'pool_operators' => ['Operador Hidroeléctrico'],
                'pool_governance' => ['Junta Directiva', 'Comité Técnico'],
                'trading_rules' => ['Servicios de balanceo', 'Reserva de regulación'],
                'settlement_procedures' => ['Liquidación horaria', 'Servicios auxiliares'],
                'risk_management' => ['Seguros de responsabilidad', 'Gestión de caudales'],
                'performance_metrics' => ['Tiempo de respuesta', 'Precisión de regulación'],
                'environmental_data' => ['Impacto en ecosistemas acuáticos'],
                'regulatory_documents' => ['Concesión hidroeléctrica', 'Permisos ambientales'],
                'tags' => ['hidroelectrica', 'balanceo', 'zamora', 'regulacion'],
                'managed_by' => $users->skip(2)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subMonths(12),
                'notes' => 'Pool crítico para estabilidad del sistema eléctrico',
            ],
            [
                'pool_number' => 'POOL-CAPACITY-004',
                'name' => 'Pool de Capacidad de Almacenamiento',
                'description' => 'Pool de almacenamiento energético con baterías de litio.',
                'pool_type' => EnergyPool::POOL_TYPE_CAPACITY,
                'status' => EnergyPool::STATUS_MAINTENANCE,
                'energy_category' => EnergyPool::ENERGY_CATEGORY_STORAGE,
                'total_capacity_mw' => 50.00,
                'available_capacity_mw' => 0.00,
                'reserved_capacity_mw' => 50.00,
                'utilized_capacity_mw' => 0.00,
                'efficiency_rating' => 92.0,
                'availability_factor' => 0.0,
                'capacity_factor' => 0.0,
                'annual_production_mwh' => 0.00,
                'monthly_production_mwh' => 0.00,
                'daily_production_mwh' => 0.00,
                'hourly_production_mwh' => 0.00,
                'location_address' => 'Centro de Almacenamiento Energético, Valencia',
                'latitude' => 39.4699,
                'longitude' => -0.3763,
                'region' => 'Valencia',
                'country' => 'España',
                'commissioning_date' => Carbon::now()->subMonths(6),
                'expected_lifespan_years' => 15,
                'construction_cost' => 75000000.00,
                'operational_cost_per_mwh' => 35.50,
                'maintenance_cost_per_mwh' => 15.25,
                'technical_specifications' => 'Baterías de litio-ferrofosfato, sistema de gestión BMS',
                'environmental_impact' => 'Reducción de 200,000 kg CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa de almacenamiento',
                'safety_features' => 'Sistema de extinción automática, ventilación forzada',
                'pool_members' => ['Almacenamiento Energético S.L.', 'Baterías del Sur'],
                'pool_operators' => ['Operador de Almacenamiento'],
                'pool_governance' => ['Comité Técnico', 'Comité de Seguridad'],
                'trading_rules' => ['Carga/descarga programada', 'Reserva de capacidad'],
                'settlement_procedures' => ['Liquidación por servicios', 'Garantías de rendimiento'],
                'risk_management' => ['Seguros de baterías', 'Cobertura de degradación'],
                'performance_metrics' => ['Eficiencia de carga/descarga', 'Ciclos de vida'],
                'environmental_data' => ['Reciclaje de baterías', 'Impacto ambiental'],
                'regulatory_documents' => ['Permisos de almacenamiento', 'Certificados de seguridad'],
                'tags' => ['almacenamiento', 'baterias', 'valencia', 'capacidad'],
                'managed_by' => $users->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->first()->id,
                'approved_at' => Carbon::now()->subMonths(3),
                'notes' => 'En mantenimiento programado - actualización de sistemas',
            ],
            [
                'pool_number' => 'POOL-DEMAND-005',
                'name' => 'Pool de Respuesta a la Demanda',
                'description' => 'Pool de gestión de demanda y respuesta de consumidores.',
                'pool_type' => EnergyPool::POOL_TYPE_DEMAND_RESPONSE,
                'status' => EnergyPool::STATUS_PLANNED,
                'energy_category' => EnergyPool::ENERGY_CATEGORY_DEMAND,
                'total_capacity_mw' => 25.75,
                'available_capacity_mw' => 0.00,
                'reserved_capacity_mw' => 25.75,
                'utilized_capacity_mw' => 0.00,
                'efficiency_rating' => 85.0,
                'availability_factor' => 0.0,
                'capacity_factor' => 0.0,
                'annual_production_mwh' => 0.00,
                'monthly_production_mwh' => 0.00,
                'daily_production_mwh' => 0.00,
                'hourly_production_mwh' => 0.00,
                'location_address' => 'Centro de Control de Demanda, Barcelona',
                'latitude' => 41.3851,
                'longitude' => 2.1734,
                'region' => 'Cataluña',
                'country' => 'España',
                'commissioning_date' => null,
                'expected_lifespan_years' => 20,
                'construction_cost' => 25000000.00,
                'operational_cost_per_mwh' => 18.75,
                'maintenance_cost_per_mwh' => 8.50,
                'technical_specifications' => 'Sistema de gestión de demanda, contadores inteligentes',
                'environmental_impact' => 'Reducción de 100,000 kg CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa de respuesta a demanda',
                'safety_features' => 'Sistema de desconexión automática', 'pool_members' => ['Gestión de Demanda S.L.', 'Consumidores Inteligentes'],
                'pool_operators' => ['Operador de Demanda'],
                'pool_governance' => ['Comité de Consumidores', 'Comité Técnico'],
                'trading_rules' => ['Reducción de demanda', 'Incentivos por participación'],
                'settlement_procedures' => ['Liquidación por reducción', 'Bonificaciones'],
                'risk_management' => ['Seguros de responsabilidad', 'Garantías de respuesta'],
                'performance_metrics' => ['Tiempo de respuesta', 'Precisión de reducción'],
                'environmental_data' => ['Reducción de emisiones', 'Eficiencia energética'],
                'regulatory_documents' => ['Permisos de operación', 'Contratos de respuesta'],
                'tags' => ['demanda', 'respuesta', 'barcelona', 'consumidores'],
                'managed_by' => $users->skip(1)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Pool en fase de planificación - inicio previsto en 6 meses',
            ],
        ];

        foreach ($pools as $pool) {
            EnergyPool::firstOrCreate(
                ['pool_number' => $pool['pool_number']],
                $pool
            );
        }

        $this->command->info('✅ EnergyPoolSeeder ejecutado correctamente');
        $this->command->info('📊 Pools energéticos creados: ' . count($pools));
        $this->command->info('🎯 Tipos de pools: Trading, Reserva, Balanceo, Capacidad, Respuesta a Demanda');
        $this->command->info('📈 Estados: Activos (3), Mantenimiento (1), Planificados (1)');
        $this->command->info('⚡ Capacidad total: ' . number_format(collect($pools)->sum('total_capacity_mw'), 2) . ' MW');
        $this->command->info('🌱 Categorías: Renovables, Híbridos, Almacenamiento, Demanda');
        $this->command->info('📍 Regiones: Madrid, Galicia, Castilla y León, Valencia, Cataluña');
        $this->command->info('💰 Inversión total: €' . number_format(collect($pools)->sum('construction_cost'), 2));
        $this->command->info('📊 Datos realistas: Capacidades, eficiencias y métricas operativas');
    }
}
