<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductionProject;
use App\Models\User;
use Carbon\Carbon;

class ProductionProjectSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::take(5)->get();
        if ($users->isEmpty()) {
            $this->command->warn('⚠️ No hay usuarios disponibles. Saltando ProductionProjectSeeder.');
            return;
        }

        $projects = [
            [
                'project_number' => 'PROJ-SOLAR-001',
                'name' => 'Parque Solar Fotovoltaico Madrid Norte',
                'description' => 'Instalación de 50 MW de energía solar fotovoltaica en el norte de Madrid.',
                'project_type' => ProductionProject::PROJECT_TYPE_SOLAR_FARM,
                'status' => ProductionProject::STATUS_IN_PROGRESS,
                'priority' => ProductionProject::PRIORITY_HIGH,
                'start_date' => Carbon::now()->subMonths(6),
                'expected_completion_date' => Carbon::now()->addMonths(6),
                'budget' => 45000000.00,
                'spent_amount' => 22500000.00,
                'remaining_budget' => 22500000.00,
                'planned_capacity_mw' => 50.00,
                'actual_capacity_mw' => 25.00,
                'efficiency_rating' => 92.5,
                'location_address' => 'Parque Solar Madrid Norte, Carretera A-1, Km 15',
                'latitude' => 40.4168,
                'longitude' => -3.7038,
                'technical_specifications' => 'Paneles monocristalinos de alta eficiencia, inversores centralizados',
                'environmental_impact' => 'Reducción de 25,000 toneladas CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa RD 244/2019',
                'safety_measures' => 'Sistema de desconexión automática, vallado perimetral',
                'project_team' => ['Ingeniero Jefe', 'Supervisor de Obra', 'Técnico de Seguridad'],
                'stakeholders' => ['Ayuntamiento de Madrid', 'Red Eléctrica de España'],
                'contractors' => ['SolarTech S.L.', 'Instalaciones Eléctricas Norte'],
                'suppliers' => ['PanelSolar Corp', 'InversorMax S.A.'],
                'milestones' => ['Cimentación completada', 'Instalación de paneles 50%', 'Conexión a red'],
                'risks' => ['Retrasos meteorológicos', 'Escasez de materiales'],
                'mitigation_strategies' => ['Planificación flexible', 'Contratos de suministro garantizado'],
                'quality_standards' => ['ISO 9001', 'Certificación CE'],
                'documentation' => ['Plan de proyecto', 'Estudios ambientales', 'Permisos'],
                'tags' => ['solar', 'fotovoltaico', 'madrid', 'renovable'],
                'project_manager' => $users->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->skip(1)->first()->id,
                'approved_at' => Carbon::now()->subMonths(8),
                'notes' => 'Proyecto prioritario para cumplir objetivos de renovables',
            ],
            [
                'project_number' => 'PROJ-WIND-002',
                'name' => 'Parque Eólico Costa da Morte',
                'description' => 'Instalación de 30 MW de energía eólica en la costa gallega.',
                'project_type' => ProductionProject::PROJECT_TYPE_WIND_FARM,
                'status' => ProductionProject::STATUS_APPROVED,
                'priority' => ProductionProject::PRIORITY_MEDIUM,
                'start_date' => Carbon::now()->addMonths(2),
                'expected_completion_date' => Carbon::now()->addMonths(14),
                'budget' => 36000000.00,
                'spent_amount' => 0.00,
                'remaining_budget' => 36000000.00,
                'planned_capacity_mw' => 30.00,
                'actual_capacity_mw' => 0.00,
                'efficiency_rating' => 0.00,
                'location_address' => 'Costa da Morte, A Coruña',
                'latitude' => 43.2627,
                'longitude' => -8.4115,
                'technical_specifications' => 'Turbinas eólicas de 3 MW, altura de buje 120m',
                'environmental_impact' => 'Reducción de 15,000 toneladas CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa eólica nacional',
                'safety_measures' => 'Sistema de parada automática, señalización aeronáutica',
                'project_team' => ['Director de Proyecto', 'Ingeniero Eólico'],
                'stakeholders' => ['Xunta de Galicia', 'Red Eléctrica de España'],
                'contractors' => ['Eólica Galicia S.L.'],
                'suppliers' => ['WindPower Corp', 'TowerTech S.A.'],
                'milestones' => ['Estudios de viento', 'Instalación de turbinas', 'Conexión a red'],
                'risks' => ['Condiciones meteorológicas adversas', 'Protestas locales'],
                'mitigation_strategies' => ['Estudios detallados', 'Comunicación con comunidades'],
                'quality_standards' => ['ISO 14001', 'Certificación IEC'],
                'documentation' => ['Estudio de impacto ambiental', 'Permisos administrativos'],
                'tags' => ['eolica', 'galicia', 'costa', 'renovable'],
                'project_manager' => $users->skip(1)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->skip(2)->first()->id,
                'approved_at' => Carbon::now()->subMonths(1),
                'notes' => 'Proyecto en fase de planificación avanzada',
            ],
            [
                'project_number' => 'PROJ-HYDRO-003',
                'name' => 'Central Hidroeléctrica del Duero',
                'description' => 'Modernización de central hidroeléctrica de 25 MW en Zamora.',
                'project_type' => ProductionProject::PROJECT_TYPE_HYDROELECTRIC,
                'status' => ProductionProject::STATUS_COMPLETED,
                'priority' => ProductionProject::PRIORITY_MEDIUM,
                'start_date' => Carbon::now()->subYears(2),
                'expected_completion_date' => Carbon::now()->subMonths(3),
                'actual_completion_date' => Carbon::now()->subMonths(2),
                'budget' => 28000000.00,
                'spent_amount' => 27500000.00,
                'remaining_budget' => 500000.00,
                'planned_capacity_mw' => 25.00,
                'actual_capacity_mw' => 25.00,
                'efficiency_rating' => 95.8,
                'location_address' => 'Central Hidroeléctrica del Duero, Zamora',
                'latitude' => 41.5035,
                'longitude' => -5.7448,
                'technical_specifications' => 'Turbinas Francis modernizadas, sistema de control digital',
                'environmental_impact' => 'Mejora de eficiencia, reducción de emisiones',
                'regulatory_compliance' => 'Cumple normativa hidroeléctrica actualizada',
                'safety_measures' => 'Sistema de alivio de presión, monitoreo sísmico',
                'project_team' => ['Ingeniero Hidráulico', 'Supervisor de Modernización'],
                'stakeholders' => ['Confederación Hidrográfica del Duero'],
                'contractors' => ['Hidroeléctrica del Duero S.L.'],
                'suppliers' => ['HydroTurbine Corp', 'ControlSystems S.A.'],
                'milestones' => ['Desmantelamiento antiguo', 'Instalación nueva', 'Pruebas de funcionamiento'],
                'risks' => ['Interrupción del suministro', 'Problemas técnicos'],
                'mitigation_strategies' => ['Plan de contingencia', 'Equipos de respaldo'],
                'quality_standards' => ['ISO 9001', 'Normativa hidroeléctrica'],
                'documentation' => ['Memoria técnica', 'Certificados de conformidad'],
                'tags' => ['hidroelectrica', 'modernizacion', 'zamora', 'duero'],
                'project_manager' => $users->skip(2)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->skip(1)->first()->id,
                'approved_at' => Carbon::now()->subYears(2)->addMonths(1),
                'notes' => 'Proyecto completado exitosamente, superando expectativas',
            ],
            [
                'project_number' => 'PROJ-STORAGE-004',
                'name' => 'Sistema de Almacenamiento Energético Valencia',
                'description' => 'Instalación de sistema de baterías de 20 MW para almacenamiento energético.',
                'project_type' => ProductionProject::PROJECT_TYPE_STORAGE,
                'status' => ProductionProject::STATUS_PLANNING,
                'priority' => ProductionProject::PRIORITY_HIGH,
                'start_date' => Carbon::now()->addMonths(3),
                'expected_completion_date' => Carbon::now()->addMonths(15),
                'budget' => 32000000.00,
                'spent_amount' => 0.00,
                'remaining_budget' => 32000000.00,
                'planned_capacity_mw' => 20.00,
                'actual_capacity_mw' => 0.00,
                'efficiency_rating' => 0.00,
                'location_address' => 'Centro de Almacenamiento Energético, Valencia',
                'latitude' => 39.4699,
                'longitude' => -0.3763,
                'technical_specifications' => 'Baterías de litio-ferrofosfato, sistema de gestión BMS',
                'environmental_impact' => 'Reducción de 10,000 toneladas CO₂ anuales',
                'regulatory_compliance' => 'Cumple normativa de almacenamiento',
                'safety_measures' => 'Sistema de extinción automática, ventilación forzada',
                'project_team' => ['Ingeniero de Almacenamiento', 'Especialista en Baterías'],
                'stakeholders' => ['Generalitat Valenciana', 'Red Eléctrica de España'],
                'contractors' => ['Almacenamiento Energético S.L.'],
                'suppliers' => ['BatteryTech Corp', 'PowerManagement S.A.'],
                'milestones' => ['Diseño técnico', 'Instalación de baterías', 'Pruebas de sistema'],
                'risks' => ['Escasez de materiales', 'Problemas técnicos'],
                'mitigation_strategies' => ['Contratos de suministro', 'Equipos de respaldo'],
                'quality_standards' => ['ISO 9001', 'Certificación de baterías'],
                'documentation' => ['Estudio técnico', 'Plan de seguridad'],
                'tags' => ['almacenamiento', 'baterias', 'valencia', 'sistema'],
                'project_manager' => $users->skip(3)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Proyecto en fase de planificación inicial',
            ],
            [
                'project_number' => 'PROJ-GRID-005',
                'name' => 'Actualización de Red Eléctrica Barcelona',
                'description' => 'Modernización de infraestructura de red eléctrica en Barcelona.',
                'project_type' => ProductionProject::PROJECT_TYPE_GRID_UPGRADE,
                'status' => ProductionProject::STATUS_ON_HOLD,
                'priority' => ProductionProject::PRIORITY_URGENT,
                'start_date' => Carbon::now()->subMonths(4),
                'expected_completion_date' => Carbon::now()->addMonths(8),
                'budget' => 15000000.00,
                'spent_amount' => 5000000.00,
                'remaining_budget' => 10000000.00,
                'planned_capacity_mw' => 0.00,
                'actual_capacity_mw' => 0.00,
                'efficiency_rating' => 0.00,
                'location_address' => 'Red Eléctrica Barcelona, Cataluña',
                'latitude' => 41.3851,
                'longitude' => 2.1734,
                'technical_specifications' => 'Subestaciones modernizadas, líneas de alta tensión',
                'environmental_impact' => 'Mejora de eficiencia de transmisión',
                'regulatory_compliance' => 'Cumple normativa de red eléctrica',
                'safety_measures' => 'Protocolos de seguridad eléctrica',
                'project_team' => ['Ingeniero de Red', 'Supervisor de Instalaciones'],
                'stakeholders' => ['Generalitat de Catalunya', 'Endesa'],
                'contractors' => ['Red Eléctrica Barcelona S.L.'],
                'suppliers' => ['GridTech Corp', 'PowerLines S.A.'],
                'milestones' => ['Planificación de cortes', 'Instalación de equipos', 'Pruebas de red'],
                'risks' => ['Interrupciones de servicio', 'Problemas de permisos'],
                'mitigation_strategies' => ['Plan de cortes programados', 'Gestión de permisos'],
                'quality_standards' => ['ISO 9001', 'Normativa eléctrica'],
                'documentation' => ['Plan de proyecto', 'Estudios de impacto'],
                'tags' => ['red', 'electricidad', 'barcelona', 'modernizacion'],
                'project_manager' => $users->skip(4)->first()->id,
                'created_by' => $users->first()->id,
                'approved_by' => $users->skip(1)->first()->id,
                'approved_at' => Carbon::now()->subMonths(6),
                'notes' => 'Proyecto en espera por problemas de permisos municipales',
            ],
        ];

        foreach ($projects as $project) {
            ProductionProject::firstOrCreate(
                ['project_number' => $project['project_number']],
                $project
            );
        }

        $this->command->info('✅ ProductionProjectSeeder ejecutado correctamente');
        $this->command->info('📊 Proyectos de producción creados: ' . count($projects));
        $this->command->info('🎯 Tipos de proyectos: Solar, Eólico, Hidroeléctrico, Almacenamiento, Red');
        $this->command->info('📈 Estados: En Progreso (1), Aprobado (1), Completado (1), Planificación (1), En Espera (1)');
        $this->command->info('⚡ Capacidad total planificada: ' . number_format(collect($projects)->sum('planned_capacity_mw'), 2) . ' MW');
        $this->command->info('💰 Presupuesto total: €' . number_format(collect($projects)->sum('budget'), 2));
        $this->command->info('📍 Ubicaciones: Madrid, Galicia, Zamora, Valencia, Barcelona');
        $this->command->info('📊 Datos realistas: Presupuestos, capacidades y cronogramas');
    }
}
