<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Transaction;
use App\Models\User;
use App\Models\Payment;
use App\Models\Invoice;
use App\Models\EnergyCooperative;
use Carbon\Carbon;

class TransactionSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::take(10)->get();
        $payments = Payment::take(5)->get();
        $invoices = Invoice::take(5)->get();
        $cooperatives = EnergyCooperative::take(3)->get();
        
        if ($users->isEmpty()) {
            $this->command->warn('⚠️ No hay usuarios disponibles. Saltando TransactionSeeder.');
            return;
        }

        $transactions = [
            [
                'transaction_code' => Transaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'batch_id' => 'BATCH-' . date('Ymd') . '-001',
                'user_id' => $users->first()->id,
                'payment_id' => $payments->first()?->id,
                'invoice_id' => $invoices->first()?->id,
                'energy_cooperative_id' => $cooperatives->first()?->id,
                'type' => 'energy_purchase',
                'category' => 'energy',
                'status' => 'completed',
                'amount' => 125.50,
                'fee' => 3.75,
                'net_amount' => 121.75,
                'currency' => 'EUR',
                'exchange_rate' => 1.0,
                'original_amount' => 125.50,
                'original_currency' => 'EUR',
                'from_account_type' => 'user_wallet',
                'from_account_id' => $users->first()->id,
                'to_account_type' => 'energy_cooperative',
                'to_account_id' => $cooperatives->first()?->id,
                'balance_before' => 500.00,
                'balance_after' => 378.25,
                'energy_amount_kwh' => 150.00,
                'energy_price_per_kwh' => 0.81,
                'energy_delivery_date' => Carbon::now()->addDays(7),
                'processed_at' => Carbon::now()->subDays(5),
                'settled_at' => Carbon::now()->subDays(5)->addHours(2),
                'processor' => 'stripe',
                'processor_transaction_id' => 'pi_' . uniqid(),
                'processor_response' => ['status' => 'succeeded', 'charge_id' => 'ch_' . uniqid()],
                'authorization_code' => 'AUTH-' . uniqid(),
                'description' => 'Compra de energía solar - 150 kWh',
                'notes' => 'Transacción procesada exitosamente',
                'metadata' => ['energy_type' => 'solar', 'kwh_amount' => 150, 'delivery_date' => Carbon::now()->addDays(7)->toDateString()],
                'created_by_id' => $users->first()->id,
                'approved_by_id' => $users->first()->id,
                'approved_at' => Carbon::now()->subDays(5),
                'ip_address' => '192.168.1.100',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_recurring' => false,
                'requires_approval' => false,
                'is_reversible' => true,
            ],
            [
                'transaction_code' => Transaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'batch_id' => 'BATCH-' . date('Ymd') . '-002',
                'user_id' => $users->skip(1)->first()->id,
                'payment_id' => $payments->skip(1)->first()?->id,
                'invoice_id' => $invoices->skip(1)->first()?->id,
                'energy_cooperative_id' => $cooperatives->skip(1)->first()?->id,
                'type' => 'subscription_fee',
                'category' => 'service',
                'status' => 'completed',
                'amount' => 89.99,
                'fee' => 0.00,
                'net_amount' => 89.99,
                'currency' => 'EUR',
                'exchange_rate' => 1.0,
                'original_amount' => 89.99,
                'original_currency' => 'EUR',
                'from_account_type' => 'user_wallet',
                'from_account_id' => $users->skip(1)->first()->id,
                'to_account_type' => 'system',
                'to_account_id' => 1,
                'balance_before' => 300.00,
                'balance_after' => 210.01,
                'processed_at' => Carbon::now()->subDays(3),
                'settled_at' => Carbon::now()->subDays(3)->addHours(1),
                'processor' => 'bank_transfer',
                'processor_transaction_id' => 'bt_' . uniqid(),
                'processor_response' => ['status' => 'completed', 'reference' => 'BT-' . uniqid()],
                'authorization_code' => 'AUTH-' . uniqid(),
                'description' => 'Cuota mensual - Plan Premium',
                'notes' => 'Suscripción renovada automáticamente',
                'metadata' => ['plan' => 'premium', 'billing_cycle' => 'monthly', 'renewal_date' => Carbon::now()->addMonth()->toDateString()],
                'created_by_id' => $users->skip(1)->first()->id,
                'approved_by_id' => $users->skip(1)->first()->id,
                'approved_at' => Carbon::now()->subDays(3),
                'ip_address' => '192.168.1.101',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_recurring' => true,
                'requires_approval' => false,
                'is_reversible' => true,
            ],
            [
                'transaction_code' => Transaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'batch_id' => 'BATCH-' . date('Ymd') . '-003',
                'user_id' => $users->skip(2)->first()->id,
                'payment_id' => $payments->skip(2)->first()?->id,
                'invoice_id' => $invoices->skip(2)->first()?->id,
                'energy_cooperative_id' => $cooperatives->skip(2)->first()?->id,
                'type' => 'energy_purchase',
                'category' => 'energy',
                'status' => 'pending',
                'amount' => 75.25,
                'fee' => 2.25,
                'net_amount' => 73.00,
                'currency' => 'EUR',
                'exchange_rate' => 1.0,
                'original_amount' => 75.25,
                'original_currency' => 'EUR',
                'from_account_type' => 'user_wallet',
                'from_account_id' => $users->skip(2)->first()->id,
                'to_account_type' => 'energy_cooperative',
                'to_account_id' => $cooperatives->skip(2)->first()?->id,
                'balance_before' => 200.00,
                'balance_after' => 127.00,
                'energy_amount_kwh' => 100.00,
                'energy_price_per_kwh' => 0.75,
                'energy_delivery_date' => Carbon::now()->addDays(5),
                'expires_at' => Carbon::now()->addHours(24),
                'processor' => 'paypal',
                'processor_transaction_id' => 'pp_' . uniqid(),
                'processor_response' => ['status' => 'pending', 'approval_url' => 'https://paypal.com/approve'],
                'description' => 'Compra de energía eólica - 100 kWh',
                'notes' => 'Esperando confirmación de PayPal',
                'metadata' => ['energy_type' => 'wind', 'kwh_amount' => 100, 'delivery_date' => Carbon::now()->addDays(5)->toDateString()],
                'created_by_id' => $users->skip(2)->first()->id,
                'ip_address' => '192.168.1.102',
                'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_recurring' => false,
                'requires_approval' => false,
                'is_reversible' => true,
            ],
            [
                'transaction_code' => Transaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'batch_id' => 'BATCH-' . date('Ymd') . '-004',
                'user_id' => $users->skip(3)->first()->id,
                'payment_id' => $payments->skip(3)->first()?->id,
                'invoice_id' => null,
                'energy_cooperative_id' => null,
                'type' => 'deposit',
                'category' => 'financial',
                'status' => 'completed',
                'amount' => 200.00,
                'fee' => 0.00,
                'net_amount' => 200.00,
                'currency' => 'EUR',
                'exchange_rate' => 1.0,
                'original_amount' => 200.00,
                'original_currency' => 'EUR',
                'from_account_type' => 'external',
                'from_account_id' => null,
                'to_account_type' => 'user_wallet',
                'to_account_id' => $users->skip(3)->first()->id,
                'balance_before' => 0.00,
                'balance_after' => 200.00,
                'processed_at' => Carbon::now()->subDays(1),
                'settled_at' => Carbon::now()->subDays(1)->addMinutes(30),
                'processor' => 'internal',
                'processor_transaction_id' => 'wallet_' . uniqid(),
                'processor_response' => ['status' => 'completed', 'wallet_balance' => 200.00],
                'authorization_code' => 'AUTH-' . uniqid(),
                'description' => 'Recarga de wallet - €200',
                'notes' => 'Depósito procesado exitosamente',
                'metadata' => ['topup_amount' => 200, 'wallet_balance' => 200, 'method' => 'bank_transfer'],
                'created_by_id' => $users->skip(3)->first()->id,
                'approved_by_id' => $users->skip(3)->first()->id,
                'approved_at' => Carbon::now()->subDays(1),
                'ip_address' => '192.168.1.103',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
                'is_internal' => true,
                'is_test' => false,
                'is_recurring' => false,
                'requires_approval' => false,
                'is_reversible' => true,
            ],
            [
                'transaction_code' => Transaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'batch_id' => 'BATCH-' . date('Ymd') . '-005',
                'user_id' => $users->skip(4)->first()->id,
                'payment_id' => $payments->skip(4)->first()?->id,
                'invoice_id' => $invoices->skip(4)->first()?->id,
                'energy_cooperative_id' => $cooperatives->first()?->id,
                'type' => 'energy_purchase',
                'category' => 'energy',
                'status' => 'failed',
                'amount' => 45.75,
                'fee' => 1.37,
                'net_amount' => 44.38,
                'currency' => 'EUR',
                'exchange_rate' => 1.0,
                'original_amount' => 45.75,
                'original_currency' => 'EUR',
                'from_account_type' => 'user_wallet',
                'from_account_id' => $users->skip(4)->first()->id,
                'to_account_type' => 'energy_cooperative',
                'to_account_id' => $cooperatives->first()?->id,
                'balance_before' => 100.00,
                'balance_after' => 100.00,
                'energy_amount_kwh' => 75.00,
                'energy_price_per_kwh' => 0.61,
                'failed_at' => Carbon::now()->subDays(2),
                'processor' => 'stripe',
                'processor_transaction_id' => 'pi_' . uniqid(),
                'processor_response' => ['status' => 'failed', 'error' => 'card_declined'],
                'description' => 'Compra de energía hidroeléctrica - 75 kWh',
                'notes' => 'Transacción fallida - Tarjeta rechazada',
                'metadata' => ['energy_type' => 'hydro', 'kwh_amount' => 75, 'error_code' => 'card_declined'],
                'failure_reason' => 'Tarjeta rechazada por el banco',
                'created_by_id' => $users->skip(4)->first()->id,
                'ip_address' => '192.168.1.104',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_recurring' => false,
                'requires_approval' => false,
                'is_reversible' => false,
            ],
            [
                'transaction_code' => Transaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'batch_id' => 'BATCH-' . date('Ymd') . '-006',
                'user_id' => $users->skip(5)->first()->id,
                'payment_id' => $payments->skip(5)->first()?->id,
                'invoice_id' => null,
                'energy_cooperative_id' => $cooperatives->first()?->id,
                'type' => 'bonus',
                'category' => 'bonus',
                'status' => 'completed',
                'amount' => 25.00,
                'fee' => 0.00,
                'net_amount' => 25.00,
                'currency' => 'EUR',
                'exchange_rate' => 1.0,
                'original_amount' => 25.00,
                'original_currency' => 'EUR',
                'from_account_type' => 'system',
                'from_account_id' => 1,
                'to_account_type' => 'user_wallet',
                'to_account_id' => $users->skip(5)->first()->id,
                'balance_before' => 150.00,
                'balance_after' => 175.00,
                'processed_at' => Carbon::now()->subHours(6),
                'settled_at' => Carbon::now()->subHours(6)->addMinutes(15),
                'processor' => 'internal',
                'processor_transaction_id' => 'bonus_' . uniqid(),
                'processor_response' => ['status' => 'completed', 'bonus_type' => 'referral'],
                'authorization_code' => 'AUTH-' . uniqid(),
                'description' => 'Bonus por referir usuario - €25',
                'notes' => 'Bonus aplicado por programa de referidos',
                'metadata' => ['bonus_type' => 'referral', 'referred_user_id' => $users->skip(6)->first()?->id, 'program' => 'referral_bonus'],
                'created_by_id' => $users->skip(5)->first()->id,
                'approved_by_id' => $users->first()->id,
                'approved_at' => Carbon::now()->subHours(6),
                'ip_address' => '192.168.1.105',
                'user_agent' => 'Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0',
                'is_internal' => true,
                'is_test' => false,
                'is_recurring' => false,
                'requires_approval' => true,
                'is_reversible' => true,
            ],
        ];

        foreach ($transactions as $transaction) {
            Transaction::firstOrCreate(
                ['transaction_code' => $transaction['transaction_code']],
                $transaction
            );
        }

        $this->command->info('✅ TransactionSeeder ejecutado correctamente');
        $this->command->info('📊 Transacciones creadas: ' . count($transactions));
        $this->command->info('💳 Tipos: Compra de energía, Cuota de suscripción, Depósito, Bonus');
        $this->command->info('📈 Estados: Completada (4), Pendiente (1), Fallida (1)');
        $this->command->info('💰 Monto total: €' . number_format(collect($transactions)->sum('amount'), 2));
        $this->command->info('⚡ Energía total: ' . number_format(collect($transactions)->sum('energy_amount_kwh'), 2) . ' kWh');
        $this->command->info('🏦 Procesadores: Stripe, PayPal, Transferencia bancaria, Interno');
        $this->command->info('🔄 Categorías: Energía, Suscripción, Wallet, Recompensa');
    }
}
