<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vendor;
use App\Models\User;
use Carbon\Carbon;

class VendorSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::take(3)->get();
        
        if ($users->isEmpty()) {
            $this->command->warn('⚠️ No hay usuarios disponibles. Saltando VendorSeeder.');
            return;
        }

        $vendors = [
            [
                'name' => 'SolarTech Solutions',
                'legal_name' => 'SolarTech Solutions S.L.',
                'tax_id' => 'B12345678',
                'registration_number' => 'REG-SOLAR-001',
                'vendor_type' => Vendor::VENDOR_TYPE_SUPPLIER,
                'industry' => 'Energía Solar',
                'description' => 'Proveedor especializado en equipos y componentes solares fotovoltaicos.',
                'contact_person' => 'María González',
                'email' => 'contacto@solartech.es',
                'phone' => '+34 91 123 4567',
                'website' => 'https://www.solartech.es',
                'address' => 'Calle Solar 123',
                'city' => 'Madrid',
                'state' => 'Madrid',
                'postal_code' => '28001',
                'country' => 'España',
                'latitude' => 40.4168,
                'longitude' => -3.7038,
                'payment_terms' => '30 días',
                'credit_limit' => 100000.00,
                'current_balance' => 0.00,
                'currency' => 'EUR',
                'tax_rate' => 21.0,
                'discount_rate' => 5.0,
                'rating' => 4.5,
                'is_active' => true,
                'is_verified' => true,
                'is_preferred' => true,
                'is_blacklisted' => false,
                'contract_start_date' => Carbon::now()->subYear(),
                'contract_end_date' => Carbon::now()->addYears(2),
                'contract_terms' => 'Contrato de suministro de equipos solares',
                'insurance_coverage' => 'Cobertura total de responsabilidad civil',
                'certifications' => json_encode(['ISO 9001', 'ISO 14001', 'CE']),
                'licenses' => json_encode(['Licencia comercial', 'Permiso ambiental']),
                'created_by' => $users->first()->id,
            ],
            [
                'name' => 'WindPower Engineering',
                'legal_name' => 'WindPower Engineering S.A.',
                'tax_id' => 'A87654321',
                'registration_number' => 'REG-WIND-002',
                'vendor_type' => Vendor::VENDOR_TYPE_CONTRACTOR,
                'industry' => 'Energía Eólica',
                'description' => 'Empresa especializada en instalación y mantenimiento de parques eólicos.',
                'contact_person' => 'Carlos Martínez',
                'email' => 'info@windpower.es',
                'phone' => '+34 93 987 6543',
                'website' => 'https://www.windpower.es',
                'address' => 'Avenida Eólica 456',
                'city' => 'Barcelona',
                'state' => 'Cataluña',
                'postal_code' => '08001',
                'country' => 'España',
                'latitude' => 41.3851,
                'longitude' => 2.1734,
                'payment_terms' => '45 días',
                'credit_limit' => 250000.00,
                'current_balance' => 15000.00,
                'currency' => 'EUR',
                'tax_rate' => 21.0,
                'discount_rate' => 3.0,
                'rating' => 4.2,
                'is_active' => true,
                'is_verified' => true,
                'is_preferred' => false,
                'is_blacklisted' => false,
                'contract_start_date' => Carbon::now()->subMonths(6),
                'contract_end_date' => Carbon::now()->addMonths(18),
                'contract_terms' => 'Contrato de servicios de mantenimiento eólico',
                'insurance_coverage' => 'Seguro de responsabilidad civil y profesional',
                'certifications' => json_encode(['ISO 9001', 'OHSAS 18001']),
                'licenses' => json_encode(['Licencia de instalación', 'Certificado técnico']),
                'created_by' => $users->skip(1)->first()->id,
            ],
            [
                'name' => 'HydroEnergy Systems',
                'legal_name' => 'HydroEnergy Systems S.L.',
                'tax_id' => 'C11223344',
                'registration_number' => 'REG-HYDRO-003',
                'vendor_type' => Vendor::VENDOR_TYPE_SERVICE_PROVIDER,
                'industry' => 'Energía Hidroeléctrica',
                'description' => 'Especialistas en sistemas hidroeléctricos y turbinas de agua.',
                'contact_person' => 'Ana Rodríguez',
                'email' => 'ventas@hydroenergy.es',
                'phone' => '+34 95 555 1234',
                'website' => 'https://www.hydroenergy.es',
                'address' => 'Plaza Hidroeléctrica 789',
                'city' => 'Sevilla',
                'state' => 'Andalucía',
                'postal_code' => '41001',
                'country' => 'España',
                'latitude' => 37.3891,
                'longitude' => -5.9845,
                'payment_terms' => '60 días',
                'credit_limit' => 50000.00,
                'current_balance' => 5000.00,
                'currency' => 'EUR',
                'tax_rate' => 21.0,
                'discount_rate' => 2.0,
                'rating' => 4.0,
                'is_active' => true,
                'is_verified' => false,
                'is_preferred' => false,
                'is_blacklisted' => false,
                'contract_start_date' => Carbon::now()->subMonths(3),
                'contract_end_date' => Carbon::now()->addMonths(12),
                'contract_terms' => 'Contrato de servicios técnicos hidroeléctricos',
                'insurance_coverage' => 'Cobertura básica de responsabilidad',
                'certifications' => json_encode(['ISO 9001']),
                'licenses' => json_encode(['Licencia comercial']),
                'created_by' => $users->skip(2)->first()->id,
            ],
            [
                'name' => 'BatteryTech Innovations',
                'legal_name' => 'BatteryTech Innovations S.L.',
                'tax_id' => 'D55667788',
                'registration_number' => 'REG-BATTERY-004',
                'vendor_type' => Vendor::VENDOR_TYPE_SUPPLIER,
                'industry' => 'Almacenamiento Energético',
                'description' => 'Proveedor líder en sistemas de almacenamiento de energía con baterías de litio.',
                'contact_person' => 'David López',
                'email' => 'comercial@batterytech.es',
                'phone' => '+34 96 777 8888',
                'website' => 'https://www.batterytech.es',
                'address' => 'Calle Batería 321',
                'city' => 'Valencia',
                'state' => 'Valencia',
                'postal_code' => '46001',
                'country' => 'España',
                'latitude' => 39.4699,
                'longitude' => -0.3763,
                'payment_terms' => '30 días',
                'credit_limit' => 200000.00,
                'current_balance' => 25000.00,
                'currency' => 'EUR',
                'tax_rate' => 21.0,
                'discount_rate' => 7.0,
                'rating' => 4.8,
                'is_active' => true,
                'is_verified' => true,
                'is_preferred' => true,
                'is_blacklisted' => false,
                'contract_start_date' => Carbon::now()->subMonths(9),
                'contract_end_date' => Carbon::now()->addMonths(15),
                'contract_terms' => 'Contrato de suministro de sistemas de almacenamiento',
                'insurance_coverage' => 'Cobertura completa de productos y responsabilidad',
                'certifications' => json_encode(['ISO 9001', 'ISO 14001', 'IEC 62619']),
                'licenses' => json_encode(['Licencia comercial', 'Certificado de calidad']),
                'created_by' => $users->first()->id,
            ],
            [
                'name' => 'SmartGrid Solutions',
                'legal_name' => 'SmartGrid Solutions S.A.',
                'tax_id' => 'E99887766',
                'registration_number' => 'REG-SMART-005',
                'vendor_type' => Vendor::VENDOR_TYPE_CONSULTANT,
                'industry' => 'Redes Inteligentes',
                'description' => 'Consultora especializada en tecnologías de redes eléctricas inteligentes.',
                'contact_person' => 'Laura Fernández',
                'email' => 'consultas@smartgrid.es',
                'phone' => '+34 98 111 2222',
                'website' => 'https://www.smartgrid.es',
                'address' => 'Avenida Smart 654',
                'city' => 'Bilbao',
                'state' => 'País Vasco',
                'postal_code' => '48001',
                'country' => 'España',
                'latitude' => 43.2627,
                'longitude' => -2.9253,
                'payment_terms' => '15 días',
                'credit_limit' => 75000.00,
                'current_balance' => 0.00,
                'currency' => 'EUR',
                'tax_rate' => 21.0,
                'discount_rate' => 0.0,
                'rating' => 4.3,
                'is_active' => true,
                'is_verified' => true,
                'is_preferred' => false,
                'is_blacklisted' => false,
                'contract_start_date' => Carbon::now()->subMonths(12),
                'contract_end_date' => Carbon::now()->addMonths(6),
                'contract_terms' => 'Contrato de consultoría en redes inteligentes',
                'insurance_coverage' => 'Seguro de responsabilidad profesional',
                'certifications' => json_encode(['ISO 9001', 'ISO 27001']),
                'licenses' => json_encode(['Licencia de consultoría']),
                'created_by' => $users->skip(1)->first()->id,
            ],
        ];

        foreach ($vendors as $vendor) {
            Vendor::create($vendor);
        }

        $this->command->info('✅ VendorSeeder ejecutado correctamente');
        $this->command->info('📊 Proveedores creados: ' . count($vendors));
        $this->command->info('🏭 Tipos: Proveedores, Contratistas, Proveedores de Servicios, Consultores');
        $this->command->info('⚡ Industrias: Solar, Eólica, Hidroeléctrica, Almacenamiento, Redes Inteligentes');
        $this->command->info('⭐ Proveedores preferidos: 2');
        $this->command->info('✅ Proveedores verificados: 4');
        $this->command->info('💰 Límite de crédito total: €' . number_format(collect($vendors)->sum('credit_limit'), 2));
        $this->command->info('📍 Ubicaciones: Madrid, Barcelona, Sevilla, Valencia, Bilbao');
    }
}