<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WalletTransaction;
use App\Models\User;
use App\Models\Transaction;
use App\Models\EnergyCooperative;
use Carbon\Carbon;

class WalletTransactionSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::take(10)->get();
        $transactions = Transaction::take(5)->get();
        $cooperatives = EnergyCooperative::take(3)->get();
        
        if ($users->isEmpty()) {
            $this->command->warn('⚠️ No hay usuarios disponibles. Saltando WalletTransactionSeeder.');
            return;
        }

        $walletTransactions = [
            [
                'transaction_code' => WalletTransaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'user_id' => $users->first()->id,
                'related_user_id' => null,
                'transaction_id' => $transactions->first()?->id,
                'energy_cooperative_id' => $cooperatives->first()?->id,
                'type' => 'credit',
                'subtype' => 'energy_purchase',
                'status' => 'completed',
                'token_type' => 'energy_credit',
                'amount' => 150.00,
                'rate' => 1.0,
                'currency' => 'EUR',
                'equivalent_value' => 150.00,
                'balance_before' => 0.00,
                'balance_after' => 150.00,
                'energy_amount_kwh' => 150.00,
                'energy_price_per_kwh' => 1.0,
                'energy_source' => 'solar',
                'is_renewable' => true,
                'energy_generation_date' => Carbon::now()->subDays(5),
                'energy_consumption_date' => Carbon::now()->addDays(7),
                'processed_at' => Carbon::now()->subDays(5),
                'expires_at' => Carbon::now()->addDays(365),
                'locked_until' => null,
                'available_at' => Carbon::now()->subDays(5),
                'description' => 'Crédito energético por compra de energía solar - 150 kWh',
                'notes' => 'Crédito generado por compra de energía renovable',
                'metadata' => ['energy_type' => 'solar', 'kwh_amount' => 150, 'renewable' => true],
                'source_wallet_id' => null,
                'source_transaction_code' => null,
                'source_amount' => null,
                'source_token_type' => null,
                'has_expiration' => true,
                'expiration_days' => 365,
                'is_locked' => false,
                'lock_reason' => null,
                'requires_approval' => false,
                'approved_by_id' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by_id' => $users->first()->id,
                'ip_address' => '192.168.1.100',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_reversible' => true,
                'reversal_transaction_id' => null,
                'reversed_at' => null,
                'reversal_reason' => null,
                'batch_id' => 'BATCH-' . date('Ymd') . '-001',
                'batch_sequence' => 1,
            ],
            [
                'transaction_code' => WalletTransaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'user_id' => $users->skip(1)->first()->id,
                'related_user_id' => null,
                'transaction_id' => $transactions->skip(1)->first()?->id,
                'energy_cooperative_id' => $cooperatives->skip(1)->first()?->id,
                'type' => 'credit',
                'subtype' => 'referral_bonus',
                'status' => 'completed',
                'token_type' => 'loyalty_point',
                'amount' => 50.00,
                'rate' => 0.5,
                'currency' => 'EUR',
                'equivalent_value' => 25.00,
                'balance_before' => 100.00,
                'balance_after' => 150.00,
                'energy_amount_kwh' => null,
                'energy_price_per_kwh' => null,
                'energy_source' => null,
                'is_renewable' => null,
                'energy_generation_date' => null,
                'energy_consumption_date' => null,
                'processed_at' => Carbon::now()->subDays(3),
                'expires_at' => Carbon::now()->addDays(180),
                'locked_until' => null,
                'available_at' => Carbon::now()->subDays(3),
                'description' => 'Puntos de lealtad por suscripción Plan Premium',
                'notes' => 'Bonus por renovación de suscripción',
                'metadata' => ['plan' => 'premium', 'bonus_type' => 'subscription_renewal'],
                'source_wallet_id' => null,
                'source_transaction_code' => null,
                'source_amount' => null,
                'source_token_type' => null,
                'has_expiration' => true,
                'expiration_days' => 180,
                'is_locked' => false,
                'lock_reason' => null,
                'requires_approval' => false,
                'approved_by_id' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by_id' => $users->skip(1)->first()->id,
                'ip_address' => '192.168.1.101',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
                'is_internal' => true,
                'is_test' => false,
                'is_reversible' => true,
                'reversal_transaction_id' => null,
                'reversed_at' => null,
                'reversal_reason' => null,
                'batch_id' => 'BATCH-' . date('Ymd') . '-002',
                'batch_sequence' => 1,
            ],
            [
                'transaction_code' => WalletTransaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'user_id' => $users->skip(2)->first()->id,
                'related_user_id' => null,
                'transaction_id' => $transactions->skip(2)->first()?->id,
                'energy_cooperative_id' => $cooperatives->skip(2)->first()?->id,
                'type' => 'debit',
                'subtype' => 'energy_purchase',
                'status' => 'pending',
                'token_type' => 'energy_credit',
                'amount' => 100.00,
                'rate' => 1.0,
                'currency' => 'EUR',
                'equivalent_value' => 100.00,
                'balance_before' => 200.00,
                'balance_after' => 100.00,
                'energy_amount_kwh' => 100.00,
                'energy_price_per_kwh' => 1.0,
                'energy_source' => 'wind',
                'is_renewable' => true,
                'energy_generation_date' => Carbon::now()->subDays(1),
                'energy_consumption_date' => Carbon::now()->addDays(5),
                'expires_at' => Carbon::now()->addHours(24),
                'locked_until' => null,
                'available_at' => null,
                'description' => 'Uso de crédito energético para compra de energía eólica - 100 kWh',
                'notes' => 'Esperando confirmación de PayPal',
                'metadata' => ['energy_type' => 'wind', 'kwh_amount' => 100, 'renewable' => true],
                'source_wallet_id' => $users->skip(2)->first()->id,
                'source_transaction_code' => null,
                'source_amount' => 100.00,
                'source_token_type' => 'energy_credit',
                'has_expiration' => true,
                'expiration_days' => 1,
                'is_locked' => false,
                'lock_reason' => null,
                'requires_approval' => false,
                'approved_by_id' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by_id' => $users->skip(2)->first()->id,
                'ip_address' => '192.168.1.102',
                'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_reversible' => true,
                'reversal_transaction_id' => null,
                'reversed_at' => null,
                'reversal_reason' => null,
                'batch_id' => 'BATCH-' . date('Ymd') . '-003',
                'batch_sequence' => 1,
            ],
            [
                'transaction_code' => WalletTransaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'user_id' => $users->skip(3)->first()->id,
                'related_user_id' => null,
                'transaction_id' => $transactions->skip(3)->first()?->id,
                'energy_cooperative_id' => null,
                'type' => 'credit',
                'subtype' => 'admin_adjustment',
                'status' => 'completed',
                'token_type' => 'cash_equivalent',
                'amount' => 200.00,
                'rate' => 1.0,
                'currency' => 'EUR',
                'equivalent_value' => 200.00,
                'balance_before' => 0.00,
                'balance_after' => 200.00,
                'energy_amount_kwh' => null,
                'energy_price_per_kwh' => null,
                'energy_source' => null,
                'is_renewable' => null,
                'energy_generation_date' => null,
                'energy_consumption_date' => null,
                'processed_at' => Carbon::now()->subDays(1),
                'expires_at' => null,
                'locked_until' => null,
                'available_at' => Carbon::now()->subDays(1),
                'description' => 'Depósito en wallet - €200',
                'notes' => 'Recarga de wallet procesada exitosamente',
                'metadata' => ['deposit_amount' => 200, 'method' => 'bank_transfer'],
                'source_wallet_id' => null,
                'source_transaction_code' => null,
                'source_amount' => null,
                'source_token_type' => null,
                'has_expiration' => false,
                'expiration_days' => null,
                'is_locked' => false,
                'lock_reason' => null,
                'requires_approval' => false,
                'approved_by_id' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by_id' => $users->skip(3)->first()->id,
                'ip_address' => '192.168.1.103',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
                'is_internal' => true,
                'is_test' => false,
                'is_reversible' => true,
                'reversal_transaction_id' => null,
                'reversed_at' => null,
                'reversal_reason' => null,
                'batch_id' => 'BATCH-' . date('Ymd') . '-004',
                'batch_sequence' => 1,
            ],
            [
                'transaction_code' => WalletTransaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'user_id' => $users->skip(4)->first()->id,
                'related_user_id' => null,
                'transaction_id' => $transactions->skip(4)->first()?->id,
                'energy_cooperative_id' => $cooperatives->first()?->id,
                'type' => 'debit',
                'subtype' => 'energy_purchase',
                'status' => 'failed',
                'token_type' => 'energy_credit',
                'amount' => 75.00,
                'rate' => 1.0,
                'currency' => 'EUR',
                'equivalent_value' => 75.00,
                'balance_before' => 100.00,
                'balance_after' => 100.00,
                'energy_amount_kwh' => 75.00,
                'energy_price_per_kwh' => 1.0,
                'energy_source' => 'hydro',
                'is_renewable' => true,
                'energy_generation_date' => Carbon::now()->subDays(2),
                'energy_consumption_date' => Carbon::now()->addDays(3),
                'processed_at' => null,
                'expires_at' => null,
                'locked_until' => null,
                'available_at' => null,
                'description' => 'Uso de crédito energético para compra de energía hidroeléctrica - 75 kWh',
                'notes' => 'Transacción fallida - Tarjeta rechazada',
                'metadata' => ['energy_type' => 'hydro', 'kwh_amount' => 75, 'renewable' => true, 'error' => 'card_declined'],
                'source_wallet_id' => $users->skip(4)->first()->id,
                'source_transaction_code' => null,
                'source_amount' => 75.00,
                'source_token_type' => 'energy_credit',
                'has_expiration' => false,
                'expiration_days' => null,
                'is_locked' => false,
                'lock_reason' => null,
                'requires_approval' => false,
                'approved_by_id' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by_id' => $users->skip(4)->first()->id,
                'ip_address' => '192.168.1.104',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'is_internal' => false,
                'is_test' => false,
                'is_reversible' => false,
                'reversal_transaction_id' => null,
                'reversed_at' => null,
                'reversal_reason' => null,
                'batch_id' => 'BATCH-' . date('Ymd') . '-005',
                'batch_sequence' => 1,
            ],
            [
                'transaction_code' => WalletTransaction::generateTransactionCode(),
                'reference' => 'REF-' . uniqid(),
                'user_id' => $users->skip(5)->first()->id,
                'related_user_id' => $users->skip(6)->first()?->id,
                'transaction_id' => null,
                'energy_cooperative_id' => null,
                'type' => 'transfer_out',
                'subtype' => 'energy_sharing',
                'status' => 'completed',
                'token_type' => 'energy_credit',
                'amount' => 25.00,
                'rate' => 1.0,
                'currency' => 'EUR',
                'equivalent_value' => 25.00,
                'balance_before' => 150.00,
                'balance_after' => 125.00,
                'energy_amount_kwh' => 25.00,
                'energy_price_per_kwh' => 1.0,
                'energy_source' => 'solar',
                'is_renewable' => true,
                'energy_generation_date' => Carbon::now()->subDays(7),
                'energy_consumption_date' => Carbon::now()->addDays(1),
                'processed_at' => Carbon::now()->subHours(6),
                'expires_at' => Carbon::now()->addDays(30),
                'locked_until' => null,
                'available_at' => Carbon::now()->subHours(6),
                'description' => 'Transferencia de crédito energético a usuario - 25 kWh',
                'notes' => 'Transferencia P2P completada',
                'metadata' => ['transfer_type' => 'peer_to_peer', 'recipient_id' => $users->skip(6)->first()?->id, 'energy_type' => 'solar'],
                'source_wallet_id' => $users->skip(5)->first()->id,
                'source_transaction_code' => null,
                'source_amount' => 25.00,
                'source_token_type' => 'energy_credit',
                'has_expiration' => true,
                'expiration_days' => 30,
                'is_locked' => false,
                'lock_reason' => null,
                'requires_approval' => false,
                'approved_by_id' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by_id' => $users->skip(5)->first()->id,
                'ip_address' => '192.168.1.105',
                'user_agent' => 'Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0',
                'is_internal' => true,
                'is_test' => false,
                'is_reversible' => true,
                'reversal_transaction_id' => null,
                'reversed_at' => null,
                'reversal_reason' => null,
                'batch_id' => 'BATCH-' . date('Ymd') . '-006',
                'batch_sequence' => 1,
            ],
        ];

        foreach ($walletTransactions as $walletTransaction) {
            WalletTransaction::firstOrCreate(
                ['transaction_code' => $walletTransaction['transaction_code']],
                $walletTransaction
            );
        }

        $this->command->info('✅ WalletTransactionSeeder ejecutado correctamente');
        $this->command->info('📊 Transacciones de wallet creadas: ' . count($walletTransactions));
        $this->command->info('💳 Tipos: Crédito (3), Débito (2), Transferencia (1)');
        $this->command->info('📈 Estados: Completada (4), Pendiente (1), Fallida (1)');
        $this->command->info('💰 Monto total: €' . number_format(collect($walletTransactions)->sum('amount'), 2));
        $this->command->info('⚡ Energía total: ' . number_format(collect($walletTransactions)->sum('energy_amount_kwh'), 2) . ' kWh');
        $this->command->info('🎯 Tipos de token: Crédito energético, Punto de lealtad, Equivalente en efectivo');
        $this->command->info('🔄 Transferencias P2P y transacciones internas incluidas');
    }
}
